# Generated by Django 3.2.12 on 2022-08-10 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time', models.DateTimeField(auto_now_add=True, verbose_name='время игры')),
                ('won', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(40)])),
                ('country', models.CharField(choices=[('K', 'Kaz'), ('R', 'Rus'), ('T', 'Tur'), ('G', 'Ger'), ('U', 'Ukr'), ('D', 'Den'), ('B', 'Bra'), ('I', 'Ita'), ('N', 'Nig'), ('S', 'Spa'), ('A', 'Aus'), ('C', 'Can'), ('P', 'Por'), ('J', 'Jap'), ('V', 'Ven')], default='K', max_length=20, verbose_name='Страна')),
                ('owner', models.IntegerField(default=0, verbose_name='id владельца')),
                ('power', models.IntegerField(default=1, verbose_name='сила')),
                ('role', models.CharField(choices=[('G', 'Goa'), ('D', 'Def'), ('M', 'Mid'), ('A', 'Att')], max_length=20, verbose_name='тип игрока')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('first_name', models.CharField(max_length=20, verbose_name='Фамилилия')),
            ],
            options={
                'verbose_name': 'Игроки',
                'verbose_name_plural': 'Игроки',
                'ordering': ('year',),
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coast', models.IntegerField(verbose_name='цена')),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SellHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_time', models.DateTimeField(auto_now_add=True, verbose_name='время покупки')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(default=10000000)),
                ('power', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(choices=[('K', 'Kaz'), ('R', 'Rus'), ('T', 'Tur'), ('G', 'Ger'), ('U', 'Ukr'), ('D', 'Den'), ('B', 'Bra'), ('I', 'Ita'), ('N', 'Nig'), ('S', 'Spa'), ('A', 'Aus'), ('C', 'Can'), ('P', 'Por'), ('J', 'Jap'), ('V', 'Ven')], default='K', max_length=20, verbose_name='Страна')),
            ],
        ),
    ]
