# Generated by Django 3.2.12 on 2022-08-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='power',
        ),
        migrations.DeleteModel(
            name='GameHistory',
        ),
    ]
