# Generated by Django 3.2.12 on 2022-08-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20220814_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='power',
        ),
    ]
